class EmojiCode:
    RED_CIRCLE = '🔴'
    RED_HEART = '❤️'
    ORANGE_CIRCLE = '🟠'
    ORANGE_HEART = '🧡'
    YELLOW_CIRCLE = '🟡'
    YELLOW_HEART = '💛'
    YELLOW_STAR = '⭐'
    GREEN_CIRCLE = '🟢'
    GREEN_HEART = '💚'
    BLUE_CIRCLE = '🔵'
    BLUE_HEART = '💙'
    PURPLE_CIRCLE = '🟣'
    PURPLE_HEART = '💜'
    BROWN_CIRCLE = '🟤'
    BROWN_HEART = '🤎'
    WHITE_CIRCLE = '⚪️'
    WHITE_HEART = '🤍'
    BLACK_CIRCLE = '⚫️'
    BLACK_HEART = '🖤'

    BOOKSTACK = '📚'
    GREEN_BOOK = '📗'
    ORANGE_BOOK = '📙'
    BLUE_BOOK = '📘'
    BROWN_NOTEBOOK = '📔'
    YELLOW_NOTEBOOK = '📒'
    BLACK_NOTEBOOK = '📓'

    ORANGE_DIAMOND = '🔶'
    GREEN_XBOX = '❎'
    GLOBE_ASIA = '🌏'
    CLOCK_1230 = '🕧'
    DIRECT_HIT = '🎯'
    SILVER_CD = '💿'
    VOLLEYBALL = '🏐'

    CYCLE = '🔁'
    CHECKER_FLAG = '🏁'
    YARN = '🧶'
    THREAD = '🧵'
    CALENDAR = '📆'
    BIG_CALENDAR = '📅'
    TIMER = '⏲️'  # 가끔 Notion 환경에 뒤 공백이 짤려 삽입된 경우가 있다.
