import datetime

database_query_parsed = [
    {
        'back_relationX': ['e15c62be-b9e4-4bb5-9b62-9220804fe93f'],
        'checkboxX': False,
        'created_timeX': '2021-06-17T10:47:00.000Z',
        'fileX': [],
        'formulaX': {'number': 123, 'type': 'number'},
        'multi_selectX': [],
        'peopleX': [],
        'relationX': ['9ed7d4fe-3c29-4e66-a4ed-cfa450814653'],
        'rollupX': [[]],
        'rollupX2': [['1234 1647 ',
                      [{'text': {'content': '1234 ', 'link': None}, 'type': 'text'},
                       {'mention': {
                           'page': {'id': 'e15c62be-b9e4-4bb5-9b62-9220804fe93f'},
                           'type': 'page'},
                        'type': 'mention'},
                       {'text': {'content': ' ', 'link': None}, 'type': 'text'}]]],
        '속성': ['150 가나다 23610',
               [{'mention': {'page': {'id': 'a6a64f5c-0ed7-4127-a86b-72ac5b77c8db'},
                             'type': 'page'},
                 'type': 'mention'},
                {'text': {'content': ' 가나다 ', 'link': None}, 'type': 'text'},
                {'mention': {'page': {'id': '3009f442-5e13-4828-9067-fbd574f31b49'},
                             'type': 'page'},
                 'type': 'mention'}]],
        '이름': ['23610',
               [{'text': {'content': '23610', 'link': None}, 'type': 'text'}]]
    },
    {
        'back_relationX': ['3009f442-5e13-4828-9067-fbd574f31b49'],
        'checkboxX': False,
        'created_timeX': '2021-06-17T10:47:00.000Z',
        'fileX': [],
        'formulaX': {'number': 123, 'type': 'number'},
        'multi_selectX': [],
        'peopleX': [],
        'relationX': [],
        'rollupX': [],
        'rollupX2': [],
        '속성': ['1234 1647 ',
               [{'text': {'content': '1234 ', 'link': None}, 'type': 'text'},
                {'mention': {'page': {'id': 'e15c62be-b9e4-4bb5-9b62-9220804fe93f'},
                             'type': 'page'},
                 'type': 'mention'},
                {'text': {'content': ' ', 'link': None}, 'type': 'text'}]],
        '이름': ['2580',
               [{'text': {'content': '2580', 'link': None}, 'type': 'text'}]]
    }
]
database_query_parsed2 = {
    [{'id': '3009f442-5e13-4828-9067-fbd574f31b49',
      'properties': {'back_relationX': ['e15c62be-b9e4-4bb5-9b62-9220804fe93f'],
                     'checkboxX': False,
                     'created_timeX': '2021-06-17T10:47:00.000Z',
                     'dateX': {'end': None,
                               'start': datetime.datetime(2021, 7, 1, 0, 0,
                                                          tzinfo=datetime.timezone(
                                                              datetime.timedelta(
                                                                  seconds=32400)))},
                     'fileX': [],
                     'formulaX': 123,
                     'multi_selectX': [],
                     'peopleX': [],
                     'relationX': ['9ed7d4fe-3c29-4e66-a4ed-cfa450814653'],
                     'rollupX': [[]],
                     'rollupX2': [['1234 1647 ',
                                   [{'text': {'content': '1234 ', 'link': None},
                                     'type': 'text'},
                                    {'mention': {'page': {
                                        'id': 'e15c62be-b9e4-4bb5-9b62-9220804fe93f'},
                                                 'type': 'page'},
                                     'type': 'mention'},
                                    {'text': {'content': ' ', 'link': None},
                                     'type': 'text'}]]],
                     '속성': ['150 가나다 23610',
                            [{'mention': {
                                'page': {'id': 'a6a64f5c-0ed7-4127-a86b-72ac5b77c8db'},
                                'type': 'page'},
                              'type': 'mention'},
                             {'text': {'content': ' 가나다 ', 'link': None},
                              'type': 'text'},
                             {'mention': {
                                 'page': {'id': '3009f442-5e13-4828-9067-fbd574f31b49'},
                                 'type': 'page'},
                              'type': 'mention'}]],
                     '열': 123,
                     '이름': ['23610',
                            [{'text': {'content': '23610', 'link': None},
                              'type': 'text'}]]}},
     {'id': 'cc0ddd3c-d233-474a-afe9-0b2d959e2675',
      'properties': {'back_relationX': [],
                     'checkboxX': False,
                     'created_timeX': '2021-07-01T05:50:00.000Z',
                     'dateX': {'end': datetime.datetime(2021, 7, 2, 10, 0,
                                                        tzinfo=datetime.timezone(
                                                            datetime.timedelta(
                                                                seconds=32400))),
                               'start': datetime.datetime(2021, 7, 1, 4, 0,
                                                          tzinfo=datetime.timezone(
                                                              datetime.timedelta(
                                                                  seconds=32400)))},
                     'fileX': [],
                     'formulaX': 123,
                     'multi_selectX': [],
                     'peopleX': [],
                     'relationX': [],
                     'rollupX': [],
                     'rollupX2': [],
                     '속성': ['', []],
                     '열': 234,
                     '이름': ['240',
                            [{'text': {'content': '240', 'link': None},
                              'type': 'text'}]]}},
     {'id': '9ed7d4fe-3c29-4e66-a4ed-cfa450814653',
      'properties': {'back_relationX': ['3009f442-5e13-4828-9067-fbd574f31b49'],
                     'checkboxX': False,
                     'created_timeX': '2021-06-17T10:47:00.000Z',
                     'dateX': {'end': None,
                               'start': datetime.datetime(2021, 7, 1, 0, 0)},
                     'fileX': [],
                     'formulaX': 123,
                     'multi_selectX': [],
                     'peopleX': [],
                     'relationX': [],
                     'rollupX': [],
                     'rollupX2': [],
                     '속성': ['1234 1647 ',
                            [{'text': {'content': '1234 ', 'link': None},
                              'type': 'text'},
                             {'mention': {
                                 'page': {'id': 'e15c62be-b9e4-4bb5-9b62-9220804fe93f'},
                                 'type': 'page'},
                              'type': 'mention'},
                             {'text': {'content': ' ', 'link': None},
                              'type': 'text'}]],
                     '열': 123,
                     '이름': ['2580',
                            [{'text': {'content': '2580', 'link': None},
                              'type': 'text'}]]}}]
}
