page_retrieve = {
    'archived': False,
    'created_time': '2021-06-14T06:56:00.000Z',
    'id': '5720981f-aa3e-4632-846f-46f990b6779d',
    'last_edited_time': '2021-06-17T07:25:00.000Z',
    'object': 'page',
    'parent': {'database_id': '5c021bea-3e29-41f3-9bff-902cb2ebfe47',
               'type': 'database_id'},
    'properties': {'back_relationX': {'id': 'Nf[_',
                                      'relation': [],
                                      'type': 'relation'},
                   'checkboxX': {'checkbox': False,
                                 'id': '_=tU',
                                 'type': 'checkbox'},
                   'created_timeX': {'created_time': '2021-06-14T06:56:00.000Z',
                                     'id': '`S?H',
                                     'type': 'created_time'},
                   'dateX': {'date': {'end': None, 'start': '2021-06-14'},
                             'id': 'sed<',
                             'type': 'date'},
                   'emailX': {'email': '123', 'id': '^Hae', 'type': 'email'},
                   'fileX': {'files': [], 'id': 'rphx', 'type': 'files'},
                   'formulaX': {'formula': {'number': 123, 'type': 'number'},
                                'id': 'oTSh',
                                'type': 'formula'},
                   'multi_selectX': {'id': '`f`<',
                                     'multi_select': [{'color': 'purple',
                                                       'id': '05bfb990-ff88-4a77-8d1b-168938008aaa',
                                                       'name': 'a'}],
                                     'type': 'multi_select'},
                   'peopleX': {'id': ':{tp',
                               'people': [{'avatar_url': None,
                                           'id': 'a007d150-bc67-422c-87db-030a71867dd9',
                                           'name': 'Younghoon Yun',
                                           'object': 'user',
                                           'person': {'email': 'dyhn78@snu.ac.kr'},
                                           'type': 'person'}],
                               'type': 'people'},
                   'relationX': {'id': 'CWgv',
                                 'relation': [
                                     {'id': '6ec57963-a8e6-4fb9-afa2-bf01ccc6dcf7'},
                                     {'id': '9e2efdc4-308c-4ec6-97df-765db284f128'}],
                                 'type': 'relation'},
                   'rollupX': {'id': 'nOH@',
                               'rollup': {'array': [{'person': [
                                   {'id': '3f836617-e73a-43f4-9505-e054559de65f',
                                    'object': 'user'},
                                   {'avatar_url': None,
                                    'id': 'a007d150-bc67-422c-87db-030a71867dd9',
                                    'name': 'Younghoon '
                                            'Yun',
                                    'object': 'user',
                                    'person': {'email': 'dyhn78@snu.ac.kr'},
                                    'type': 'person'}],
                                                     'type': 'person'},
                                                    {'person': [{'avatar_url': None,
                                                                 'id': 'a007d150-bc67-422c-87db-030a71867dd9',
                                                                 'name': 'Younghoon '
                                                                         'Yun',
                                                                 'object': 'user',
                                                                 'person': {
                                                                     'email': 'dyhn78@snu.ac.kr'},
                                                                 'type': 'person'},
                                                                {
                                                                    'id': '3f836617-e73a-43f4-9505-e054559de65f',
                                                                    'object': 'user'}],
                                                     'type': 'person'}],
                                          'type': 'array'},
                               'type': 'rollup'},
                   'rollupX2': {'id': ']rOg',
                                'rollup': {
                                    'array': [{'text': [{'annotations': {'bold': False,
                                                                         'code': False,
                                                                         'color': 'default',
                                                                         'italic': False,
                                                                         'strikethrough': False,
                                                                         'underline': False},
                                                         'href': None,
                                                         'plain_text': '1234 ',
                                                         'text': {'content': '1234 ',
                                                                  'link': None},
                                                         'type': 'text'},
                                                        {'annotations': {'bold': False,
                                                                         'code': False,
                                                                         'color': 'default',
                                                                         'italic': False,
                                                                         'strikethrough': False,
                                                                         'underline': False},
                                                         'href': 'https://www.notion.so/e15c62beb9e44bb59b629220804fe93f',
                                                         'mention': {'page': {
                                                             'id': 'e15c62be-b9e4-4bb5-9b62-9220804fe93f'},
                                                             'type': 'page'},
                                                         'plain_text': 'Untitled',
                                                         'type': 'mention'},
                                                        {'annotations': {'bold': False,
                                                                         'code': False,
                                                                         'color': 'default',
                                                                         'italic': False,
                                                                         'strikethrough': False,
                                                                         'underline': False},
                                                         'href': None,
                                                         'plain_text': ' ',
                                                         'text': {'content': ' ',
                                                                  'link': None},
                                                         'type': 'text'}],
                                               'type': 'text'},
                                              {'text': [], 'type': 'text'}],
                                    'type': 'array'},
                                'type': 'rollup'},
                   'selectX': {'id': 'f[Wf',
                               'select': {'color': 'green',
                                          'id': '9780409b-7c94-4b4c-bbdb-27138e4f7222',
                                          'name': '1'},
                               'type': 'select'},
                   'telephoneX': {'id': 'QSB_',
                                  'phone_number': '123',
                                  'type': 'phone_number'},
                   'urlX': {'id': 'UFxg', 'type': 'url', 'url': '123'},
                   '속성': {'id': 'lL@a',
                          'rich_text': [{'annotations': {'bold': False,
                                                         'code': False,
                                                         'color': 'default',
                                                         'italic': False,
                                                         'strikethrough': False,
                                                         'underline': False},
                                         'href': None,
                                         'plain_text': 'asd',
                                         'text': {'content': 'asd', 'link': None},
                                         'type': 'text'}],
                          'type': 'rich_text'},
                   '이름': {'id': 'title',
                          'title': [{'annotations': {'bold': False,
                                                     'code': False,
                                                     'color': 'default',
                                                     'italic': False,
                                                     'strikethrough': False,
                                                     'underline': False},
                                     'href': None,
                                     'plain_text': '1',
                                     'text': {'content': '1', 'link': None},
                                     'type': 'text'}],
                          'type': 'title'}},
    'url': 'https://www.notion.so/1-5720981faa3e4632846f46f990b6779d'
}
