class EmojiCode:
    RED_CIRCLE = '🔴'
    RED_HEART = '❤'
    ORANGE_HEART = '🟠'
    ORANGE_CIRCLE = '🧡'
    ORANGE_DIAMOND = '🔶'
    YELLOW_CIRCLE = '🟡'
    YELLOW_HEART = '💛'
    GREEN_CIRCLE = '🟢'
    GREEN_HEART = '💚'
    BLUE_CIRCLE = '🔵'
    BLUE_HEART = '💙'
    PURPLE_CIRCLE = '🟣'
    PURPLE_HEART = '💜'
    BROWN_CIRCLE = '🟤'
    BROWN_HEART = '🤎'

    BOOKSTACK = '📚'
    GREEN_BOOK = '📗'
    ORANGE_BOOK = '📙'
    BLUE_BOOK = '📘'
    BROWN_NOTEBOOK = '📔'
    YELLOW_NOTEBOOK = '📒'
    BLACK_NOTEBOOK = '📓'

    CYCLE = '🔁'
    CHECKER_FLAG = '🏁'
    YARN = '🧶'
    THREAD = '🧵'
    CALENDAR = '📆'
    BIG_CALENDAR = '📅'
    TIMER = '⏲️'  # 가끔 Notion 환경에 뒤 공백이 짤려 삽입된 경우가 있다.
    GLOBE_ASIA = '🌏'
