properties = {'ㄱㄴㄷㄹ': {'id': 'ED`J', 'number': 1234, 'type': 'number'},
              '날짜⏲️_raw': {'created_time': '2021-07-05T11:11:00.000Z',
                           'id': '?O^_',
                           'type': 'created_time'},
              '날짜값_모두': {'id': 'YKss',
                         'rollup': {'array': [{'formula': {'date': {'end': None,
                                                                    'start': '2021-07-04T15:00:00.000+00:00'},
                                                           'type': 'date'},
                                               'type': 'formula'},
                                              {'formula': {'date': {'end': None,
                                                                    'start': '2021-07-03T15:00:00.000+00:00'},
                                                           'type': 'date'},
                                               'type': 'formula'}],
                                    'type': 'array'},
                         'type': 'rollup'},
              '날짜값⏲️': {'formula': {'date': {'end': None,
                                             'start': '2021-07-05T00:00:00.000+00:00'},
                                    'type': 'date'},
                        'id': 'yf>B',
                        'type': 'formula'},
              '날짜값📘': {'id': '<fjT',
                        'rollup': {'date': {'end': None,
                                            'start': '2021-07-03T15:00:00.000+00:00'},
                                   'type': 'date'},
                        'type': 'rollup'},
              '분값📘': {'formula': {'number': None, 'type': 'number'},
                       'id': '@B{M',
                       'type': 'formula'},
              '시각값📘': {'formula': {'number': None, 'type': 'number'},
                        'id': 'uwTE',
                        'type': 'formula'},
              '🏁작성': {'id': '26184031-0177-400d-947f-0f62c4fb8cd8',
                       'select': {'color': 'yellow',
                                  'id': 'fa84bf24-a209-45bc-a826-1597051ec866',
                                  'name': '➕정리'},
                       'type': 'select'},
              '🏁작성=S': {'formula': {'string': '➕정리', 'type': 'string'},
                         'id': 'chMM',
                         'type': 'formula'},
              '📆환경/시간': {'id': 'TkLD', 'rich_text': [], 'type': 'rich_text'},
              '📓내용': {'id': 'Fo;P', 'multi_select': [], 'type': 'multi_select'},
              '📓내용.-일지/사진': {'formula': {'string': '', 'type': 'string'},
                              'id': 'wQkg',
                              'type': 'formula'},
              '📖바탕': {'id': '\\qQb', 'multi_select': [], 'type': 'multi_select'},
              '📖정서': {'id': '3bc0d034-2c3b-4b11-89c3-7fad1b0a13f2',
                       'multi_select': [],
                       'type': 'multi_select'},
              '📖행위+정서=S': {'formula': {'string': '', 'type': 'string'},
                            'id': 'Vyk{',
                            'type': 'formula'},
              '📗음악': {'id': 'O;=Y',
                       'relation': [{'id': '25e034a2-c106-461e-8728-57471c106a4c'}],
                       'type': 'relation'},
              '📘기간': {'id': 'bxe@', 'relation': [], 'type': 'relation'},
              '📘날짜': {'id': '<Vx;',
                       'relation': [{'id': '9535bede-6a94-4d79-8794-535d816e3612'},
                                    {'id': 'c54e78c9-3bcd-45dc-ae8c-aed985faa68a'}],
                       'type': 'relation'},
              '📘수행=S': {'id': 'uB?S',
                         'rollup': {'array': [{'relation': [], 'type': 'relation'},
                                              {'relation': [], 'type': 'relation'},
                                              {'relation': [], 'type': 'relation'}],
                                    'type': 'array'},
                         'type': 'rollup'},
              '📘안배+읽기=S': {'id': 'VQr}',
                            'rollup': {'array': [{'formula': {'string': None,
                                                              'type': 'string'},
                                                  'type': 'formula'},
                                                 {'formula': {'string': None,
                                                              'type': 'string'},
                                                  'type': 'formula'},
                                                 {'formula': {'string': None,
                                                              'type': 'string'},
                                                  'type': 'formula'}],
                                       'type': 'array'},
                            'type': 'rollup'},
              '📘읽기=S': {'id': 'SNxb',
                         'rollup': {'array': [{'relation': [], 'type': 'relation'},
                                              {'relation': [], 'type': 'relation'},
                                              {'relation': [], 'type': 'relation'}],
                                    'type': 'array'},
                         'type': 'rollup'},
              '📙인물': {'id': 'b@FK', 'relation': [], 'type': 'relation'},
              '📙일과': {'id': 'tu_t',
                       'relation': [{'id': 'a1bc81b4-4505-47eb-bb8c-45c5390f6b8e'}],
                       'type': 'relation'},
              '📙장소': {'id': '=mNM', 'relation': [], 'type': 'relation'},
              '📚번호': {'formula': {'string': 'ㄱ320', 'type': 'string'},
                       'id': 'F:LX',
                       'type': 'formula'},
              '📚제목': {'id': 'title',
                       'title': [{'annotations': {'bold': False,
                                                  'code': False,
                                                  'color': 'default',
                                                  'italic': False,
                                                  'strikethrough': False,
                                                  'underline': False},
                                  'href': None,
                                  'plain_text': 'ㄱ320',
                                  'text': {'content': 'ㄱ320', 'link': None},
                                  'type': 'text'}],
                       'type': 'title'},
              '📦이동': {'id': '?xGz', 'relation': [], 'type': 'relation'},
              '🕕간략': {'formula': {'string': ' N11:11', 'type': 'string'},
                       'id': '}nTS',
                       'type': 'formula'},
              '🕕날짜값': {'formula': {'date': {'end': None,
                                             'start': '2021-07-05T00:00:00.000+00:00'},
                                    'type': 'date'},
                        'id': 'IBX[',
                        'type': 'formula'},
              '🕕날짜값/달력': {'formula': {'string': '/', 'type': 'string'},
                           'id': '?Hf{',
                           'type': 'formula'},
              '🕕달력': {'formula': {'string': None, 'type': 'string'},
                       'id': 'PSqS',
                       'type': 'formula'},
              '🕕시간': {'formula': {'string': '', 'type': 'string'},
                       'id': '>MqV',
                       'type': 'formula'},
              '🕕일시': {'formula': {'date': {'end': None,
                                            'start': '2021-07-05T11:11:00.000+00:00'},
                                   'type': 'date'},
                       'id': '[RxZ',
                       'type': 'formula'},
              '🧵쓰기': {'id': '<UIy',
                       'relation': [{'id': '59ea2a47-9981-4dba-b007-44ab776a17cf'}],
                       'type': 'relation'},
              '🧵진도': {'id': 'n{U}',
                       'relation': [{'id': '7a1eb598-abdb-48e7-b8fe-275d8d07a1e6'},
                                    {'id': '6588df37-0c50-4e83-a5cd-0592313db67a'},
                                    {'id': 'd117b6b3-1053-4b5d-a050-67551a87484d'}],
                       'type': 'relation'}}
